### ISSUE TITLE
Error when extracting place from osm.pbf

### ISSUE THREAD

**Issue by mustafapiynirci** [openstreetmap/osmosis#116]
The flags I run osmosis with: `--read-pbf file="C:\europe-latest.osm.pbf" --tf accept-nodes "place=country,state,region,province,district,county,municipality,city,town,village,hamlet,isolated_dwelling,farm,allotments" --tf reject-ways --tf reject-relations --sort --read-pbf file="C:\europe-latest.osm.pbf" --tf accept-ways "place=country,state,region,province,district,county,municipality,city,town,village,hamlet,isolated_dwelling,farm,allotments" --tf reject-relations --used-node --sort --read-pbf file="C:\europe-latest.osm.pbf" --tf accept-relations "place=country,state,region,province,district,county,municipality,city,town,village,hamlet,isolated_dwelling,farm,allotments" --used-way --used-node --sort --merge --merge --write-pbf granularity=10000 "europe-places.osm.pbf"`

```
apr 01, 2022 10:00:06 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.48.3
apr 01, 2022 10:00:06 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
apr 01, 2022 10:00:06 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
apr 01, 2022 10:00:06 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
apr 01, 2022 10:54:29 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-pbf failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: An output error has occurred, aborting.
        at org.openstreetmap.osmosis.core.store.DataPostbox.checkForOutputErrors(DataPostbox.java:162)
        at org.openstreetmap.osmosis.core.store.DataPostbox.populateCentralQueue(DataPostbox.java:218)
        at org.openstreetmap.osmosis.core.store.DataPostbox.put(DataPostbox.java:305)
        at org.openstreetmap.osmosis.set.v0_6.impl.DataPostboxSink.process(DataPostboxSink.java:45)
        at org.openstreetmap.osmosis.core.sort.v0_6.SortedEntityPipeValidator.process(SortedEntityPipeValidator.java:68)
        at org.openstreetmap.osmosis.core.sort.v0_6.EntitySorter.complete(EntitySorter.java:80)
        at org.openstreetmap.osmosis.tagfilter.v0_6.TagFilter.complete(TagFilter.java:150)
        at org.openstreetmap.osmosis.tagfilter.v0_6.TagFilter.complete(TagFilter.java:150)
        at org.openstreetmap.osmosis.tagfilter.v0_6.TagFilter.complete(TagFilter.java:150)
        at crosby.binary.osmosis.OsmosisBinaryParser.complete(OsmosisBinaryParser.java:35)
        at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:37)
        at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:45)
        at java.lang.Thread.run(Unknown Source)

apr 01, 2022 10:54:29 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 6-read-pbf failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to write long 1529723894 to the store.
        at org.openstreetmap.osmosis.core.store.DataOutputStoreWriter.writeLong(DataOutputStoreWriter.java:86)
        at org.openstreetmap.osmosis.core.domain.v0_6.CommonEntityData.store(CommonEntityData.java:215)
        at org.openstreetmap.osmosis.core.domain.v0_6.Entity.store(Entity.java:154)
        at org.openstreetmap.osmosis.core.domain.v0_6.Node.store(Node.java:201)
        at org.openstreetmap.osmosis.core.container.v0_6.NodeContainer.store(NodeContainer.java:49)
        at org.openstreetmap.osmosis.core.store.BaseObjectWriter.writeObject(BaseObjectWriter.java:63)
        at org.openstreetmap.osmosis.core.store.SimpleObjectStore.add(SimpleObjectStore.java:105)
        at org.openstreetmap.osmosis.tagfilter.v0_6.UsedNodeFilter.process(UsedNodeFilter.java:92)
        at org.openstreetmap.osmosis.core.container.v0_6.NodeContainer.process(NodeContainer.java:58)
        at org.openstreetmap.osmosis.tagfilter.v0_6.UsedNodeFilter.process(UsedNodeFilter.java:75)
        at org.openstreetmap.osmosis.tagfilter.v0_6.TagFilter.process(TagFilter.java:141)
        at org.openstreetmap.osmosis.tagfilter.v0_6.TagFilter.process(TagFilter.java:141)
        at crosby.binary.osmosis.OsmosisBinaryParser.parseDense(OsmosisBinaryParser.java:138)
        at org.openstreetmap.osmosis.osmbinary.BinaryParser.parse(BinaryParser.java:124)
        at org.openstreetmap.osmosis.osmbinary.BinaryParser.handleBlock(BinaryParser.java:68)
        at org.openstreetmap.osmosis.osmbinary.file.FileBlock.process(FileBlock.java:135)
        at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:34)
        at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:45)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: There is not enough space on the disk
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(Unknown Source)
        at java.util.zip.DeflaterOutputStream.deflate(Unknown Source)
        at java.util.zip.DeflaterOutputStream.write(Unknown Source)
        at java.util.zip.GZIPOutputStream.write(Unknown Source)
        at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.io.BufferedOutputStream.write(Unknown Source)
        at java.io.DataOutputStream.writeLong(Unknown Source)
        at org.openstreetmap.osmosis.core.store.DataOutputStoreWriter.writeLong(DataOutputStoreWriter.java:84)
        ... 18 more

apr 01, 2022 10:54:29 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 11-read-pbf failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to write integer 527535939 to the store.
        at org.openstreetmap.osmosis.core.store.DataOutputStoreWriter.writeInteger(DataOutputStoreWriter.java:74)
        at org.openstreetmap.osmosis.core.domain.v0_6.Node.store(Node.java:203)
        at org.openstreetmap.osmosis.core.container.v0_6.NodeContainer.store(NodeContainer.java:49)
        at org.openstreetmap.osmosis.core.store.BaseObjectWriter.writeObject(BaseObjectWriter.java:63)
        at org.openstreetmap.osmosis.core.store.SimpleObjectStore.add(SimpleObjectStore.java:105)
        at org.openstreetmap.osmosis.tagfilter.v0_6.UsedWayFilter.process(UsedWayFilter.java:90)
        at org.openstreetmap.osmosis.core.container.v0_6.NodeContainer.process(NodeContainer.java:58)
        at org.openstreetmap.osmosis.tagfilter.v0_6.UsedWayFilter.process(UsedWayFilter.java:73)
        at org.openstreetmap.osmosis.tagfilter.v0_6.TagFilter.process(TagFilter.java:141)
        at crosby.binary.osmosis.OsmosisBinaryParser.parseDense(OsmosisBinaryParser.java:138)
        at org.openstreetmap.osmosis.osmbinary.BinaryParser.parse(BinaryParser.java:124)
        at org.openstreetmap.osmosis.osmbinary.BinaryParser.handleBlock(BinaryParser.java:68)
        at org.openstreetmap.osmosis.osmbinary.file.FileBlock.process(FileBlock.java:135)
        at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:34)
        at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:45)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: There is not enough space on the disk
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(Unknown Source)
        at java.util.zip.DeflaterOutputStream.deflate(Unknown Source)
        at java.util.zip.DeflaterOutputStream.write(Unknown Source)
        at java.util.zip.GZIPOutputStream.write(Unknown Source)
        at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.io.BufferedOutputStream.write(Unknown Source)
        at java.io.DataOutputStream.writeInt(Unknown Source)
        at org.openstreetmap.osmosis.core.store.DataOutputStoreWriter.writeInteger(DataOutputStoreWriter.java:72)
        ... 15 more

apr 01, 2022 10:54:29 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 16-merge failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: An input error has occurred, aborting.
        at org.openstreetmap.osmosis.core.store.DataPostbox.checkForInputErrors(DataPostbox.java:174)
        at org.openstreetmap.osmosis.core.store.DataPostbox.consumeCentralQueue(DataPostbox.java:244)
        at org.openstreetmap.osmosis.core.store.DataPostbox.hasNext(DataPostbox.java:441)
        at org.openstreetmap.osmosis.set.v0_6.EntityMerger.nextOrNull(EntityMerger.java:290)
        at org.openstreetmap.osmosis.set.v0_6.EntityMerger.run(EntityMerger.java:126)
        at java.lang.Thread.run(Unknown Source)

apr 01, 2022 10:54:29 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 17-merge failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: An input error has occurred, aborting.
        at org.openstreetmap.osmosis.core.store.DataPostbox.checkForInputErrors(DataPostbox.java:174)
        at org.openstreetmap.osmosis.core.store.DataPostbox.consumeCentralQueue(DataPostbox.java:244)
        at org.openstreetmap.osmosis.core.store.DataPostbox.hasNext(DataPostbox.java:441)
        at org.openstreetmap.osmosis.set.v0_6.EntityMerger.nextOrNull(EntityMerger.java:290)
        at org.openstreetmap.osmosis.set.v0_6.EntityMerger.run(EntityMerger.java:126)
        at java.lang.Thread.run(Unknown Source)

apr 01, 2022 10:54:29 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

**Comment by brettch** [comment]
It looks like you've run out of disk space ...
```
Caused by: java.io.IOException: There is not enough space on the disk
```
