### ISSUE TITLE
Osmosis not working at all

### ISSUE THREAD

**Issue by nembo22** [openstreetmap/osmosis#152]
I installed the latest version of osmosis, along with jdk 21, on my Windows pc but it doesn't seem to work at all. For every command it says execution aborted. It also reports a warning at the start. This is an exemple of the errors I get:

```
C:\Users\pepit>osmosis --read-pbf "C:\\Users\\pepit\\Desktop\\Università\\R studio\\dati_raw\\osm_extract_full.pbf"
nov 06, 2024 3:11:20 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.49.2
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
nov 06, 2024 3:11:20 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
nov 06, 2024 3:11:20 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: The following named pipes () and 1 default pipes have not been terminated with appropriate output sinks.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.connectTasks(Pipeline.java:96)
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.prepare(Pipeline.java:116)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:86)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
```

I also get an error while using java through R that may be related:

```
Errore in .jcall("RJavaTools", "Z", "hasField", .jcast(x, "java/lang/Object"),  : 
  java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "<parameter1>" is null
```

I really hope someone can help me solve this problem, I didn't manage to figure it out at all...

**Comment by kdhanka** [comment]
[Osmium.v116.win64.zip](https://github.com/user-attachments/files/18308892/Osmium.v116.win64.zip)

I had the same problem.  I tried every Osmosis build going back a year, they all have the same bug.

I eventually gave up and switched to Osmium, which required a whole separate brouhaha to build, but I've now got a working win64 version, and have successfully used it to groom and merge my PBFs. I attached a copy of it to this post, but you can also msg me if you want to verify I'm a real human.

**Comment by brettch** [comment]
The reason this command is failing is because no destination has been specified for the data.

The `--read-pbf` task reads data in from a PBF file but has nowhere to send the results, hence the error message `The following named pipes () and 1 default pipes have not been terminated with appropriate output sinks.`.

If you just want to test that `--read-pbf` is working you could try adding the `--write-null` task at the end to discard all output.
`osmosis --read-pbf "C:\\Users\\pepit\\Desktop\\Università\\R studio\\dati_raw\\osm_extract_full.pbf" --write-null`

If you want to see what the contents of the PBF file look like you could write it out to a human readable XML format.
`osmosis --read-pbf "C:\\Users\\pepit\\Desktop\\Università\\R studio\\dati_raw\\osm_extract_full.pbf" --write-xml data.xml`

**Comment by kdhanka** [comment]
I think we have a winner for the 2024 "World's Most Inscrutable Error Message" award.
