### ISSUE TITLE
update all films / shows crashes osmisis

### ISSUE THREAD

**Issue by steel4me** [openstreetmap/osmosis#79]
dont know when this exactly happened. i do not often update all films / shows. 

```
2020-10-25 10:20:16.589 T:4932   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "C:\Users\TV\AppData\Roaming\Kodi\addons\plugin.video.osmosis\default.py", line 78, in <module>
                                                strm_update(actor=int(params.get('updateActor', 0)))
                                              File "C:\Users\TV\AppData\Roaming\Kodi\addons\plugin.video.osmosis\resources\lib\updateAll.py", line 83, in strm_update
                                                fillPluginItems(url, strm=True, strm_name=name, strm_type=cType, name_orig=name_orig, pDialog=pDialog)
                                              File "C:\Users\TV\AppData\Roaming\Kodi\addons\plugin.video.osmosis\resources\lib\create.py", line 76, in fillPluginItems
                                                addMovies(details, strm_name, strm_type, name_orig, pDialog)
                                              File "C:\Users\TV\AppData\Roaming\Kodi\addons\plugin.video.osmosis\resources\lib\create.py", line 491, in addMovies
                                                m_title = cleanLabels(contentList[0].get('name'), keep_year=settings.KEEP_MOVIE_YEAR)
                                              File "C:\Users\TV\AppData\Roaming\Kodi\addons\plugin.video.osmosis\resources\lib\stringUtils.py", line 49, in cleanLabels
                                                text = multiple_reSub(text, dictresub)
                                              File "C:\Users\TV\AppData\Roaming\Kodi\addons\plugin.video.osmosis\resources\lib\utils.py", line 69, in multiple_reSub
                                                text = re.sub(i, j, text)
                                              File "C:\Program Files\Kodi\system\python\Lib\re.py", line 155, in sub
                                                return _compile(pattern, flags).sub(repl, string, count)
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--
```

**Comment by mmd-osm** [comment]
Definitely wrong repo, this has nothing to do with Kodi. Please close this one and try elsewhere.

**Comment by steel4me** [comment]
uhhhh im very sorry!
