### ISSUE TITLE
ERROR: insert or update on table "current_way_nodes" violates foreign key constraint "current_way_nodes_node_id_fkey"

### ISSUE THREAD

**Issue by hthouse** [openstreetmap/osmosis#99]
While using the following osmosis command to sync data from the planet dump, 

osmosis --read-xml-change file=so-and-so.osc --write-apidb-change host=$HOSTNAME database=$DATABASE user=$USERNAME password=$PASSWORD validateSchemaVersion=no

but we are getting the following error:
[2:03 PM] Bharadwaj, Kireet
org.openstreetmap.osmosis.core.OsmosisRuntimeException: **Unable to insert current way node with way id=6510672 and node id=9092467749.**
45 at org.openstreetmap.osmosis.apidb.v0_6.impl.ChangeWriter.write(ChangeWriter.java:706)
46 at org.openstreetmap.osmosis.apidb.v0_6.impl.ActionChangeWriter.process(ActionChangeWriter.java:56)
47 at org.openstreetmap.osmosis.core.container.v0_6.WayContainer.process(WayContainer.java:58)
48 at org.openstreetmap.osmosis.apidb.v0_6.ApidbChangeWriter.process(ApidbChangeWriter.java:81)
49 at org.openstreetmap.osmosis.xml.v0_6.impl.ChangeSourceElementProcessor$ChangeSinkAdapter.process(ChangeSourceElementProcessor.java:144)
50 at org.openstreetmap.osmosis.xml.v0_6.impl.WayElementProcessor.end(WayElementProcessor.java:117)
51 at org.openstreetmap.osmosis.xml.v0_6.impl.OsmChangeHandler.endElement(OsmChangeHandler.java:94)
52 at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
53 at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
54 at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
55 at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
56 at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
57 at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
58 at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
59 at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
60 at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
61 at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
62 at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
63 at org.openstreetmap.osmosis.xml.v0_6.impl.BaseXMLReader.parseXML(BaseXMLReader.java:65)
64 at org.openstreetmap.osmosis.xml.v0_6.impl.BaseXMLReader.handleXML(BaseXMLReader.java:77)
65 at org.openstreetmap.osmosis.xml.v0_6.XmlChangeReader.run(XmlChangeReader.java:51)
66 at java.base/java.lang.Thread.run(Thread.java:829)
**67 Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "current_way_nodes" violates foreign key constraint "current_way_nodes_node_id_fkey"
68 Detail: Key (node_id)=(9092467749) is not present in table "current_nodes".**
69 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
70 at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
71 at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
72 at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
73 at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
74 at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
75 at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
76 at org.openstreetmap.osmosis.apidb.v0_6.impl.ChangeWriter.write(ChangeWriter.java:702)
77 ... 21 more

**Comment by Andygol** [comment]
I faced the same issue of deploying incomplete data into API DB. 🤕 
This [answer from help.osm.org](https://help.openstreetmap.org/questions/8630/osmosis-stops-with-error-insert-or-update-on-table-current_way_nodes-violates-foreign-key-constraint-current_way_nodes_node_id_fkey/8663) helped me to solve the issue by using `clipIncompleteEntities=true` (see https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.48#--bounding-polygon_(--bp))

```sh
osmosis \
--read-pbf-fast workers=4 file="$data_file" \
--bounding-polygon file="$poly_file" clipIncompleteEntities=true \
--write-apidb \
host="$POSTGRES_HOST"  \
database="$POSTGRES_DB" \ 
user="$POSTGRES_USER"  \
password="$POSTGRES_PASSWORD \
validateSchemaVersion=no \
allowIncorrectSchemaVersion=yes  
```
